#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Holberton School

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' > /var/www/html/index.html
sudo printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;
    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;
}"
> /etc/nginx/sites-available/default

sudo service nginx start
