#!/usr/bin/env bash
#install and configure Nginx on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo hello world > /tmp/test
printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;
    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;
}"
> /etc/nginx/sites-available/default

service nginx start
