#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get install nginx -y

sudo ufw allow "Nginx HTTP"

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html

sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
printf %s "server {                                      listen 80 default_server;                             listen [::]:80 default_server;                                                                              root /var/www/html;                                   index index.html index.htm index.nginx-debian.html;
	location /redirect_me {
	   return 301 https://intranet.alxswe.com/projects/266;
   }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx reload
