#!/usr/bin/env bash
# redirects to new page error 301
apt-get -y update
apt-get install nginx -y

ufw allow "Nginx HTTP"

mkdir -p /var/www/html
touch /var/www/html/index.html

chown -R "$USER":"$USER" /var/www/html/index.html
chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
printf %s "server {                                      listen 80 default_server;                             listen [::]:80 default_server;                                                                              root /var/www/html;                                   index index.html index.htm index.nginx-debian.html;
	location /redirect_me {
	   return 301 https://intranet.alxswe.com/projects/266;
   }
}" > /etc/nginx/sites-available/default

service nginx reload
