#!/usr/bin/env bash                                   # Installs Nginx with the following configurations:   #+    Listens on port 80.                             #+    Returns a page containing "Holberton School" when queried                                             #++    at the root with a curl GET request.
                                                      sudo apt-get -y update
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'                                                                                 sudo mkdir -p /var/www/html                           sudo touch /var/www/html/index.html
sudo touch /var/www/html/custom_404.html

sudo chown -R $USER:$USER /var/www/html/index.html
sudo chown -R $USER:$USER /var/www/html/custom_404.html
sudo chown -R $USER:$USER /etc/nginx/sites-available/default
                                                      sudo echo "Hello World!" > /var/www/html/index.html
						      sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
						      sudo printf %s "server {                                      listen 80 default_server;                             listen [::]:80 default_server;                                                                              root /var/www/html;                                   index index.html index.htm index.nginx-debian.html;
	location /redirect_me {
	   return 301 https://intranet.alxswe.com/projects/266;
   }

	error_page 404 /custom_404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default
