#!/usr/bin/env bash
apt-get -y update
apt-get install nginx -y

ufw allow "Nginx HTTP"

mkdir -p /var/www/html

touch /var/www/html/index.html
touch /var/www/html/custom_404.html

chown -R "$USER":"$USER" /var/www/html/index.html
chown -R "$USER":"$USER" /var/www/html/custom_404.html
chown -R "$USER":"$USER" /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	location /redirect_me {
		return 301 https://intranet.alxswe.com/projects/266;
	}

	error_page 404 /custom_404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default
