#!/usr/bin/env bash
#configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"


sudo apt-get -y update
sudo apt-get -y install nginx

sudo touch /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html

sudo printf %s "server {
    listen		80 default_server;
        listen		[::]:80 default_server;
	    root		/var/www/html;
	        index		index.html index.htm index.nginx-debian.html;
		    location /redirect_me {
		            return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
			        }
		}
	" > /etc/nginx/sites-available/default

	sudo service nginx restart
