#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install -y haproxy=2.8.\*
sudo chown -R $USER:$USER /etc/haproxy/haproxy.cfg
sudo chown -R $USER:$USER /etc/default/haproxy
sudo chmod -R 755 /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  50000
    timeout server  50000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    http-response set-header Connection keep-alive
    server web-01 18.233.62.178:80 check
    server web-02 174.129.55.177:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
sudo systemctl enable haproxy.service

sudo systemctl restart haproxy.service
